# Please write the FULL release version *exactly* as it appears in GitHub. This affects the download links:
current_release: v0.1.0-alpha
current_release_cycle: v0.1.x-alpha
base_url: http://shearofdoom.github.io/Cactus
